module.exports = {
  apps: [
    {
      name: 'nextjs-dashboard',
      script: 'npm',
      args: 'run start -- --port 3200',
      cwd: '/home/weruby/Dev_AI/web',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: '/tmp/nextjs-error.log',
      out_file: '/tmp/nextjs-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        PORT: 3200,
      },
    },
    {
      name: 'api-server',
      script: 'python',
      args: '-m uvicorn main:app --port 4500 --host 0.0.0.0',
      cwd: '/home/weruby/Dev_AI/api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      error_file: '/tmp/api-error.log',
      out_file: '/tmp/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      interpreter: '/home/weruby/Dev_AI/api/venv/bin/python',
    },
  ],
};
